# Generated by Django 4.1.2 on 2022-10-18 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('Sale', 'sale'), ('Rent', 'rent')], max_length=4)),
                ('area_sqms', models.FloatField()),
                ('price', models.FloatField()),
                ('rooms', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=30)),
                ('subarea', models.CharField(max_length=25)),
                ('geolocation', models.CharField(max_length=45)),
                ('pool', models.BooleanField()),
                ('security', models.BooleanField()),
                ('reception', models.BooleanField()),
                ('garbage', models.BooleanField()),
                ('conditioning', models.BooleanField()),
                ('pets', models.BooleanField()),
                ('green_area', models.BooleanField()),
                ('gym', models.BooleanField()),
                ('wifi', models.BooleanField()),
                ('sauna', models.BooleanField()),
                ('parking', models.BooleanField()),
                ('cleaning', models.BooleanField()),
                ('dstv', models.BooleanField()),
                ('generator', models.BooleanField()),
                ('ptype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.propertytype')),
            ],
        ),
    ]
