# Generated by Django 4.1.2 on 2022-10-19 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='price',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='home',
            name='ptype',
            field=models.ForeignKey(default='Any Status', on_delete=django.db.models.deletion.CASCADE, to='main.propertytype'),
        ),
        migrations.AlterField(
            model_name='home',
            name='status',
            field=models.CharField(choices=[('Sale', 'sale'), ('Rent', 'rent')], default='Any Status', max_length=4),
        ),
    ]
