# Generated by Django 4.1.2 on 2022-10-19 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_home_description_alter_home_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='ptype',
            field=models.ForeignKey(default='Any Type', on_delete=django.db.models.deletion.CASCADE, to='main.propertytype'),
        ),
    ]
