# Generated by Django 4.1.2 on 2022-10-19 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_home_ptype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='status',
            field=models.CharField(choices=[('Sale', 'sale'), ('Rent', 'rent')], default='Any Status', max_length=40),
        ),
        migrations.AlterField(
            model_name='propertytype',
            name='types',
            field=models.CharField(max_length=40),
        ),
    ]
