# Generated by Django 4.1.2 on 2022-10-19 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_home_status_alter_propertytype_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='status',
            field=models.CharField(choices=[('Sale', 'sale'), ('Rent', 'rent'), ('Any Status', 'Any Status')], default='Any Status', max_length=30),
        ),
    ]
