# Generated by Django 4.1.2 on 2022-10-19 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_home_ptype_alter_propertytype_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='ptype',
            field=models.ForeignKey(default='Any Type', on_delete=django.db.models.deletion.CASCADE, to='main.propertytype'),
        ),
        migrations.AlterField(
            model_name='propertytype',
            name='types',
            field=models.CharField(max_length=40),
        ),
    ]
