# Generated by Django 4.1.2 on 2022-10-19 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_home_ptype_alter_propertytype_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertytype',
            name='types',
            field=models.CharField(default='Any Type', max_length=40),
        ),
    ]
