# Generated by Django 4.1.2 on 2022-10-19 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_propertytype_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='status',
            field=models.CharField(choices=[('Sale', 'sale'), ('Rent', 'rent'), ('Any Status', 'Any Status')], default='Any Status', max_length=40),
        ),
    ]
