# Generated by Django 4.1.2 on 2022-10-19 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_home_ptype_alter_home_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='bath',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='bed',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
