# Generated by Django 4.1.2 on 2022-10-19 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_home_bath_home_bed'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='created_att',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='updated_att',
            field=models.TimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='updated_at',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
