# Generated by Django 4.1.2 on 2022-10-20 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_home_created_att_remove_home_updated_att_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='image',
            field=models.ImageField(default='images/p1.jpg', upload_to=''),
            preserve_default=False,
        ),
    ]
