# Generated by Django 4.1.2 on 2022-10-20 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_home_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='image',
        ),
        migrations.AddField(
            model_name='home',
            name='images',
            field=models.ImageField(default='images/p1.jpg', upload_to='images/'),
            preserve_default=False,
        ),
    ]
