# Generated by Django 4.1.2 on 2022-10-20 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_home_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='images',
        ),
    ]
