# Generated by Django 4.1.2 on 2022-10-21 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_home_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertytype',
            name='types',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
