# Generated by Django 4.1.2 on 2022-10-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_home_ptype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertytype',
            name='types',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
    ]
