# Generated by Django 4.1.2 on 2022-10-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_propertytype_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertytype',
            name='types',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
    ]
